name: optimized_cached_image
description: A library for loading images from network, resizing as per container size and caching while being memory sensitive.
version: 2.0.0
homepage: https://github.com/humblerookie/optimized_cached_image

environment:
  sdk: ">=2.6.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^2.1.2
  flutter_image_compress: ^0.7.0
  uuid: ^2.2.2
  http: ^0.12.2
  path_provider: ^1.6.28
  path: ^1.7.0
  pedantic: ^1.9.2
  sprintf: ^5.0.0
  octo_image: ^0.3.0
  image: ^2.1.19
  file: ^5.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter